import socket
import os
import sys
import time
import random
import math
import pickle
import json
import base64
import hmac
import hashlib
import secrets

from sympy import randprime

#from Cryptodome.Cipher import AES
#from Cryptodome.Util import Counter


from Crypto.Cipher import AES
from Crypto.Util import Counter

# ─────────────────────────────────────────────────────────────────────────────
#  Public / fixed parameters  (hardcoded — not secret, same as setup script)
# ─────────────────────────────────────────────────────────────────────────────
n = 32
m = 32

tao   = 2 ** 60
M     = 102805560819865375360034795775555166450266292837454042697409287522006925995901

#p     = 4023638685153034690284565268330197297
#p_inv = pow(p, -1, M)


hmac_key = bytes.fromhex("f5430c07fb46d973598958c8c52f8435")
PRF_key  = bytes.fromhex(
    "a0006eddfe982ff6bf068ae8e39578e12e3da5da9c4d6d3ee9185945129566ec"
)
prg_key  = bytes.fromhex(
    "1d73ecfe2e7974e690ca2193031b047e4322a1bd9effc2fd91041656a6491a95"
)

# ─────────────────────────────────────────────────────────────────────────────
#  Load pre-computed encrypted weights and authenticators from file
#  (generated by extprotocol-client-serv32.py — analogous to ctext.pkl)
# ─────────────────────────────────────────────────────────────────────────────
with open('et_auth.pkl', 'rb') as f:
    store = pickle.load(f)

ET   = store["ET"]    # ET[i][j] = (p*encode(TT[i][j]) + r_ij) mod M
AUTH = store["AUTH"]  # AUTH[i]  = r_i + sum_j ALPHA[j]*encode(TT[i][j]) mod M

print(f"Loaded et_auth.pkl: {len(ET)} rows x {len(ET[0])} cols of ET, {len(AUTH)} AUTH values")


print("ET (byte size in pickle):", len(pickle.dumps(ET)))
print ("AUTH (byte size in pickle):", len(pickle.dumps(AUTH)))
ea_size = os.path.getsize('et_auth.pkl')

print("Actual storage cost for et_auth.pkl", ea_size)
# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────
def send_all(sock, data: bytes):
    view = memoryview(data)
    while len(view):
        sent = sock.send(view)
        if sent == 0:
            raise ConnectionError("socket connection broken")
        view = view[sent:]

def recv_with_length(sock):
    length_bytes = sock.recv(4)
    total_length = int.from_bytes(length_bytes, 'big')
    data = b''
    while len(data) < total_length:
        data += sock.recv(total_length - len(data))
    return data

# ─────────────────────────────────────────────────────────────────────────────
#  f(c): given challenge c (length n, values +1/-1)
#
#  Computes and sends:
#    emu[i] = sum_{j=0}^{n-1} c[j] * ET[i][j]  mod M    (m values)
#             mirrors PUF: AC_f[i] = sign( sum_j c[j]*TT[i][j] )
#    sig    = sum_{i=0}^{m-1} c[i] * AUTH[i]   mod M    (authenticator)
#             (uses c as row-selector over AUTH; valid since n == m == 32)
# ─────────────────────────────────────────────────────────────────────────────
def f(c):
    """
    c has length n.
    emu[i] = sum_{j=0}^{n-1} c[j] * ET[i][j]  mod M   for i in range(m)
    This mirrors PUF:  AC_f[i] = sign( sum_j c[j]*TT[i][j] )
    Client strips blinding to recover delta[i] = sum_j c[j]*TT[i][j]
    and checks sign(delta[i]) == AC_f[i].

    sig authenticates via ALPHA: sig = sum_i c[i]*AUTH[i]  (n==m so indexing is fine)
    """
    #t1 = time.time()

    # emu[i] = dot(c, ET[i, :])  — m values, one per TT row
    total_emu_size = 0
    emu = []
    for i in range(n):
        s = 0
        for j in range(m):
            s = s + c[j] * ET[j][i]
        emu.append(s % M)
        total_emu_size += sys.getsizeof(emu[-1])

    print("Total emu size (bytes):", total_emu_size)

    # sig = dot(c, AUTH)  using c as challenge over AUTH rows  (n == m == 32)
    sig = 0
    for i in range(m):
        sig = sig + c[i] * AUTH[i]
    sig = sig % M

    print("sig size (bytes):", sys.getsizeof(sig))

    #t2 = time.time()
    #print(f"Server proof generation time: {t2 - t1:.3f}s")

    payload = pickle.dumps({"emu": emu, "sig": sig})
    print("Total communication from server to client (bytes):", len(payload))
    send_all(client_socket, len(payload).to_bytes(4, 'big'))
    send_all(client_socket, payload)

    #print(f"Total server time: {time.time() - t1:.3f}s")
    return 0

# ─────────────────────────────────────────────────────────────────────────────
#  Socket server
# ─────────────────────────────────────────────────────────────────────────────
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
host = '127.0.0.1'
port = 12345
server_socket.bind((host, port))
server_socket.listen(1)
print(f"Server is listening on {host}:{port}")

client_socket, client_address = server_socket.accept()
print(f"Connection established with {client_address}")

data = client_socket.recv(4096)
c = pickle.loads(data)
print(f"Received challenge: c = {c}")

start = time.time()
result = f(c)

end = time.time()
print("Server time", end-start)

client_socket.close()
server_socket.close()
